from database.connection import engine
from sqlalchemy import text
import sqlglot
from sqlglot import exp


def clean_sql(sql):
    """
    Clean SQL generated by the LLM.
    Removes markdown code blocks and extra whitespace.
    """

    sql = sql.strip()

    if sql.startswith("```sql"):
        sql = sql[6:]

    elif sql.startswith("```"):
        sql = sql[3:]

    if sql.endswith("```"):
        sql = sql[:-3]

    return sql.strip()


def validate_sql(sql):
    """
    Parse SQL and allow only SELECT statements.
    """

    sql = clean_sql(sql)

    if not sql:
        raise ValueError("Generated SQL is empty.")

    try:
        parsed = sqlglot.parse(sql, dialect="mysql")

    except Exception as e:
        raise ValueError(f"Invalid SQL syntax: {e}")

    if len(parsed) != 1:
        raise ValueError("Only one SQL statement is allowed.")

    statement = parsed[0]

    # Only SELECT queries are allowed
    if not isinstance(statement, exp.Select):
        raise ValueError("Only SELECT queries are allowed.")

    return sql


def execute_sql(sql):
    """
    Validate and execute a read-only SQL query.
    """

    sql = validate_sql(sql)

    try:

        with engine.connect() as connection:

            result = connection.execute(text(sql))

            columns = list(result.keys())

            rows = [
                dict(row._mapping)
                for row in result
            ]

            return {
                "columns": columns,
                "rows": rows
            }

    except Exception as e:

        raise RuntimeError(
            f"SQL execution failed: {e}"
        )


if __name__ == "__main__":

    sql = input("Enter SQL query: ")

    try:

        result = execute_sql(sql)

        print("\nColumns:")
        print(result["columns"])

        print("\nResults:")

        if not result["rows"]:
            print("No results found.")

        else:
            for row in result["rows"]:
                print(row)

    except Exception as e:

        print("\nError:")
        print(e)